# Generated by Django 2.2.11 on 2020-03-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('function', models.CharField(max_length=200)),
                ('avatar', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
